/**
 * Template-based explanation generator.
 * Produces plain-language explanations per tier and language.
 * Content is templated/reviewed, not freely generated by LLM.
 */

const tierExplanations = {
  emergency: {
    en: 'Your symptoms may indicate a serious condition that needs immediate medical attention. Please seek emergency care right away.',
    ur: 'آپ کی علامات کسی سنگین حالت کی نشاندہی کر سکتی ہیں جسے فوری طبی توجہ کی ضرورت ہے۔ براہ کرم فوری طور پر ہنگامی طبی امداد حاصل کریں۔',
    'ur-roman': 'Aap ki alaamaat kisi sangeen halat ki nishandahi kar sakti hain jise fori tibbi tawajjuh ki zaroorat hai. Barah-e-karam fori tor par emergency medical aid hasil karein.',
    pa: 'تہاڈیاں علامات کسی سنجیدہ حالت دی نشاندہی کر سکدیاں نیں۔ فوراً ہنگامی طبی مدد لوو۔',
    ps: 'ستاسو نښې ممکن یو جدي حالت وښيي چې سمدستي درملنې ته اړتیا لري. مهرباني وکړئ سمدستي بېړنۍ پاملرنه ترلاسه کړئ.',
    sd: 'توہان جون علامتون ڪنھن سنجيده حالت جي نشاندھي ڪري سگھن ٿيون. فوري طور تي ايمرجنسي طبي مدد حاصل ڪريو.',
  },
  clinic: {
    en: 'Your symptoms suggest you should see a healthcare provider soon. Please visit a nearby clinic or hospital for a proper checkup.',
    ur: 'آپ کی علامات بتاتی ہیں کہ آپ کو جلد کسی طبی ماہر سے ملنا چاہیے۔ براہ کرم قریبی کلینک یا ہسپتال جائیں۔',
    'ur-roman': 'Aap ki alaamaat bataati hain ke aap ko jald kisi tibbi mahir se milna chahiye. Barah-e-karam qareebi clinic ya hospital jayein.',
    pa: 'تہاڈیاں علامات دسدیاں نیں کہ تسی جلدی ڈاکٹر کول جاؤ۔ نیڑے دے کلینک جاؤ۔',
    ps: 'ستاسو نښې ښیي چې تاسو باید ژر تر ژره د روغتیا پاملرنې وګورئ. مهرباني وکړئ نږدې کلینیک ته لاړشئ.',
    sd: 'توہان جون علامتون ٻڌائين ٿيون ته توہان کي جلد ڊاڪٽر وٽ وڃڻ گھرجي. ويجهو ڪلينڪ تي وڃو.',
  },
  home_care: {
    en: 'Your symptoms appear manageable at home. Rest, stay hydrated, and monitor your condition. If symptoms worsen, seek medical help.',
    ur: 'آپ کی علامات گھر پر سنبھالی جا سکتی ہیں۔ آرام کریں، پانی پیتے رہیں، اور اپنی حالت پر نظر رکھیں۔ اگر علامات بگڑیں تو طبی مدد لیں۔',
    'ur-roman': 'Aap ki alaamaat ghar par sambhaali ja sakti hain. Aaram karein, paani peetay rahein, aur apni halat par nazar rakhein. Agar alaamaat bigrein to tibbi madad lein.',
    pa: 'تہاڈیاں علامات گھر تے سنبھالیاں جا سکدیاں نیں۔ آرام کرو، پانی پیندے رہو۔ جے علامات ودھن تاں ڈاکٹر کول جاؤ۔',
    ps: 'ستاسو نښې په کور کې د سمبالولو وړ ښکاري. آرام وکړئ، اوبه وڅکئ، او خپل حالت وڅارئ.',
    sd: 'توہان جون علامتون گھر تي سنڀالي سگھجن ٿيون. آرام ڪريو، پاڻي پيئندا رهو. جيڪڏهن علامتون وڌن ته ڊاڪٽر وٽ وڃو.',
  },
};

const homeCareGuidance = {
  en: {
    title: 'Self-Care Guidance',
    tips: [
      'Rest and take it easy',
      'Drink plenty of fluids',
      'Monitor your symptoms',
      'If symptoms get worse or new symptoms appear, seek medical help',
    ],
    watchFor: [
      'Difficulty breathing',
      'Severe or worsening pain',
      'High fever that does not come down',
      'Confusion or unusual drowsiness',
    ],
  },
  ur: {
    title: 'خود کی دیکھ بھال',
    tips: ['آرام کریں', 'کافی پانی پئیں', 'اپنی علامات پر نظر رکھیں', 'اگر علامات بگڑیں تو ڈاکٹر سے ملیں'],
    watchFor: ['سانس لینے میں مشکل', 'شدید درد', 'تیز بخار', 'الجھن یا غیر معمولی سستی'],
  },
  'ur-roman': {
    title: 'Khud ki dekh bhaal',
    tips: ['Aaram karein', 'Kaafi paani piyein', 'Apni alaamaat par nazar rakhein', 'Agar alaamaat bigrein to doctor se milein'],
    watchFor: ['Saans lene mein mushkil', 'Shadeed dard', 'Tez bukhaar', 'Uljhan ya gair-mamooli susti'],
  },
};

function generate(tier, rationale, language) {
  const lang = tierExplanations[tier] ? (tierExplanations[tier][language] || tierExplanations[tier].en) : null;
  return lang || tierExplanations[tier]?.en || 'Please consult a healthcare professional.';
}

function getHomeCareGuidance(language) {
  return homeCareGuidance[language] || homeCareGuidance.en;
}

module.exports = { generate, getHomeCareGuidance };
